# -*- coding: utf-8 -*-
"""eval_recruitment_judge_4models_rotator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16WJkUFBbg5hH7QXsV1681vDew58yeM4q

# Évaluation LLM — Juge sur Reports uniquement

Ce notebook :
1. Charge les reports `report_job_X_cv_Y.json` de chaque modèle depuis Drive
2. Pour chaque paire **(job, cv)** des **60 premières lignes** du dataset :
   - Le **juge génère son propre rapport de référence** en lisant JD + CV
   - Il évalue le rapport de chaque modèle par rapport à cette référence  
     (hallucinations, fiabilité, erreurs, verdict)
3. **Sauvegarde immédiate** sur Drive dès qu'un jugement est terminé  
   (fichier `judgment_jobX_cvY.json` — pas d'attente de fin de boucle)

**Providers supportés :** Groq (modèle gratuit ~70-120B) · OpenRouter (modèles gratuits)
"""

!pip install -q groq openai pandas tqdm

"""## Configuration — à modifier ici"""

!pip install groq

PROVIDER = "groq"


GROQ_MODEL     = "openai/gpt-oss-120b"

OPENROUTER_MODEL    = "qwen/qwen3-235b-a22b:free"

DRIVE_ROOT   = "/content/drive/MyDrive"
DATASET_CSV  = "gnn/job-1 (1).csv"

MODEL_DIRS = {
    "Data_70B": "gnn/Data_70B"
}

CSV_MODELS = {
    "Word2Vec_GS":  "/content/drive/MyDrive/gnn/w2v_gs_scores.csv",
    "ATS":          "/content/drive/MyDrive/gnn/ats_scores.csv",
    "GNN":          "/content/drive/MyDrive/gnn/gnn_matching_results.csv",
}


MAX_ROWS           = 60
CVS_PER_JOB        = 5
JUDGE_TEMPERATURE  = 0.1
JUDGE_MAX_TOKENS   = 2048
SLEEP_API          = 1.5
RETRIES            = 3

from datetime import datetime
OUT_DIR_NAME = f"judge_reports_{datetime.now().strftime('%Y%m%d_%H%M')}"

print(f"Provider JUGE : {PROVIDER}")
print(f"Modèle JUGE   : {GROQ_MODEL if PROVIDER=='groq' else OPENROUTER_MODEL}")
print(f"Modèles évalués : {list(MODEL_DIRS.keys()) + list(CSV_MODELS.keys())}")
print(f"Dataset  : {MAX_ROWS} premières lignes × {CVS_PER_JOB} CVs")

"""## Initialisation du client API"""

import os
import threading
from groq import Groq, RateLimitError

GROQ_API_KEYS = [k.strip() for k in os.environ.get("GROQ_API_KEYS", "").split(",") if k.strip()]

class GroqKeyRotator:
    """Tourne automatiquement sur la clé suivante en cas de RateLimitError."""

    def __init__(self, keys):
        if not keys:
            raise ValueError("Aucune clé Groq fournie dans GROQ_API_KEYS.")
        self._keys   = keys
        self._idx    = 0
        self._lock   = threading.Lock()
        self._clients = {k: Groq(api_key=k) for k in keys}
        print(f"[KeyRotator] {len(keys)} clé(s) Groq chargée(s).")

    @property
    def current_key(self):
        return self._keys[self._idx]

    @property
    def client(self):
        return self._clients[self.current_key]

    def _rotate(self):
        with self._lock:
            next_idx = (self._idx + 1) % len(self._keys)
            if next_idx == self._idx:
                raise RuntimeError("[KeyRotator] Toutes les clés Groq sont épuisées !")
            self._idx = next_idx
            print(f"[KeyRotator] Bascule sur la clé #{self._idx + 1} (sur {len(self._keys)}).")

    def chat_completions_create(self, **kwargs):
        for attempt in range(len(self._keys)):
            try:
                return self.client.chat.completions.create(**kwargs)
            except RateLimitError as e:
                print(f"[KeyRotator] RateLimitError clé #{self._idx + 1}: {e}")
                self._rotate()
        raise RuntimeError("[KeyRotator] Toutes les clés Groq sont épuisées après rotation.")

_groq_rotator = GroqKeyRotator(GROQ_API_KEYS)

GROQ_API_KEY = _groq_rotator.current_key
print("[KeyRotator] Prêt.")

import os, json, re, time
from pathlib import Path
import pandas as pd
from tqdm.notebook import tqdm

if PROVIDER == "groq":
    def llm_call(messages, temperature=JUDGE_TEMPERATURE, max_tokens=JUDGE_MAX_TOKENS):
        resp = _groq_rotator.chat_completions_create(
            model=GROQ_MODEL, temperature=temperature,
            max_tokens=max_tokens, messages=messages
        )
        return resp.choices[0].message.content.strip()

elif PROVIDER == "openrouter":
    from openai import OpenAI
    _or_client = OpenAI(
        api_key=OPENROUTER_API_KEY,
        base_url="https://openrouter.ai/api/v1",
    )

    def llm_call(messages, temperature=JUDGE_TEMPERATURE, max_tokens=JUDGE_MAX_TOKENS):
        resp = _or_client.chat.completions.create(
            model=OPENROUTER_MODEL, temperature=temperature,
            max_tokens=max_tokens, messages=messages,
            extra_headers={"HTTP-Referer": "https://eval-recruitment", "X-Title": "Eval Recruitment"}
        )
        return resp.choices[0].message.content.strip()
else:
    raise ValueError(f"Provider inconnu : {PROVIDER}. Choisissez 'groq' ou 'openrouter'.")

def safe_json_parse(text):
    """Nettoie et parse un JSON retourné par le LLM."""
    text = re.sub(r'^```(?:json)?\s*|\s*```$', '', text.strip(), flags=re.MULTILINE)
    m = re.search(r'\{.*\}', text, re.DOTALL)
    if m:
        text = m.group()
    return json.loads(text)

def call_with_retry(messages, retries=RETRIES):
    for attempt in range(retries):
        try:
            raw = llm_call(messages)
            return safe_json_parse(raw)
        except json.JSONDecodeError as e:
            print(f"  JSONDecodeError (t{attempt+1}): {e}")
            time.sleep(2 ** attempt * SLEEP_API)
        except Exception as e:
            wait = 2 ** attempt * SLEEP_API
            print(f"  Erreur API (t{attempt+1}): {e} — attente {wait:.1f}s")
            time.sleep(wait)
    return None

print(f"Client {PROVIDER} initialisé — modèle : {GROQ_MODEL if PROVIDER=='groq' else OPENROUTER_MODEL}")

"""## Montage Drive & Chargement des données"""

from google.colab import drive
drive.mount('/content/drive', force_remount=False)
print("Drive monté")

def load_dataset(csv_path, max_rows=MAX_ROWS, n_cvs=CVS_PER_JOB):
    df = pd.read_csv(csv_path, nrows=max_rows)
    dataset = {}
    for i, row in df.iterrows():
        job_id = f"job_{i}"
        entry = {"description": str(row.get("job_description_adequate", ""))}
        for k in range(1, n_cvs + 1):
            entry[f"cv_{k}"] = str(row.get(f"cv_{k}", ""))
        dataset[job_id] = entry
    return dataset

csv_path = Path(DRIVE_ROOT) / DATASET_CSV
DATASET  = load_dataset(csv_path)
print(f"Dataset chargé : {len(DATASET)} jobs (max {MAX_ROWS} lignes)")



def load_reports(model_root):
    """Charge report_job_X_cv_Y.json depuis model_root/reports/"""
    reports_dir = Path(model_root) / "reports"
    data = {}
    if not reports_dir.exists():
        print(f"  ⚠ Dossier introuvable : {reports_dir}")
        return data
    for p in reports_dir.glob("report_job_*_cv_*.json"):
        m = re.match(r"report_(job_\w+)_(cv_\w+)\.json", p.name)
        if not m:
            continue
        jid, cid = m.group(1), m.group(2)
        try:
            with open(p, encoding="utf-8") as f:
                rep = json.load(f)
            data.setdefault(jid, {})[cid] = rep
        except Exception as e:
            print(f"  Erreur lecture {p.name}: {e}")
    return data

ALL_REPORTS = {}
for model_name, rel_dir in MODEL_DIRS.items():
    path = Path(DRIVE_ROOT) / rel_dir
    reps = load_reports(path)
    ALL_REPORTS[model_name] = reps
    n = sum(len(v) for v in reps.values())
    print(f"{model_name} : {len(reps)} jobs, {n} reports JSON chargés")



def load_w2v_gs(csv_path, max_rows=MAX_ROWS):
    """
    Colonnes : job_idx, cv_col, score, score_skills, score_experience,
               score_education, score_location, label, gs_matched, justification
    Retourne : {job_id: {cv_id: report_dict}}
    """
    df = pd.read_csv(csv_path)
    df = df[df["job_idx"] <= max_rows]
    data = {}
    for _, row in df.iterrows():
        job_id = f"job_{int(row['job_idx']) - 1}"
        cv_id  = str(row["cv_col"]).strip()
        report = {
            "overall_assessment": {
                "verdict":   str(row.get("label", "")),
                "match_pct": float(row.get("score", 0)),
            },
            "final_scores": {
                "skills":     float(row.get("score_skills",     0)),
                "experience": float(row.get("score_experience", 0)),
                "education":  float(row.get("score_education",  0)),
                "location":   float(row.get("score_location",   0)),
            },
            "gs_matched":   str(row.get("gs_matched",   "")),
            "justification": str(row.get("justification", "")),
            "critical_gaps": [],
            "profile_summary": {"strengths": [], "critical_weaknesses": []},
        }
        data.setdefault(job_id, {})[cv_id] = report
    return data


def load_ats(csv_path, max_rows=MAX_ROWS):
    """
    Colonnes : job_idx, rank, cv_id, candidate, experience_years, nb_skills,
               matched_skills, keyword_score, skills_score, experience_score,
               global_score, label, job_snippet
    Retourne : {job_id: {cv_id: report_dict}}
    """
    df = pd.read_csv(csv_path)
    df = df[df["job_idx"] <= max_rows]
    data = {}
    for _, row in df.iterrows():
        job_id = f"job_{int(row['job_idx']) - 1}"
        cv_id  = f"cv_{int(row['cv_id'])}"
        matched = str(row.get("matched_skills", ""))
        report = {
            "overall_assessment": {
                "verdict":   str(row.get("label", "")),
                "match_pct": float(row.get("global_score", 0)),
            },
            "final_scores": {
                "keyword":    float(row.get("keyword_score",   0)),
                "skills":     float(row.get("skills_score",    0)),
                "experience": float(row.get("experience_score",0)),
            },
            "profile_summary": {
                "strengths":            [s.strip() for s in matched.split(",") if s.strip()],
                "critical_weaknesses":  [],
            },
            "critical_gaps":    [],
            "experience_years": float(row.get("experience_years", 0)),
            "nb_skills":        int(row.get("nb_skills", 0)),
        }
        data.setdefault(job_id, {})[cv_id] = report
    return data


def load_gnn(csv_path, max_rows=MAX_ROWS):
    """
    Colonnes : row_idx, job_snippet,
               score_cv_1..score_cv_5, label_cv_1..label_cv_5,
               predicted_best_cv, predicted_label, scores, labels
    Retourne : {job_id: {cv_id: report_dict}}
    """
    df = pd.read_csv(csv_path, nrows=max_rows)
    data = {}
    for _, row in df.iterrows():
        job_id = f"job_{int(row['row_idx'])}"
        for k in range(1, CVS_PER_JOB + 1):
            cv_id  = f"cv_{k}"
            score  = float(row.get(f"score_cv_{k}", 0))
            label  = str(row.get(f"label_cv_{k}", ""))
            best   = str(row.get("predicted_best_cv", ""))
            report = {
                "overall_assessment": {
                    "verdict":   label,
                    "match_pct": round(score * 100, 2),
                },
                "final_scores": {"gnn_similarity": score},
                "predicted_best": best == cv_id,
                "critical_gaps":  [],
                "profile_summary": {"strengths": [], "critical_weaknesses": []},
            }
            data.setdefault(job_id, {})[cv_id] = report
    return data



CSV_LOADERS = {
    "Word2Vec_GS": load_w2v_gs,
    "ATS":         load_ats,
    "GNN":         load_gnn,
}

for model_name, loader in CSV_LOADERS.items():
    csv_path = CSV_MODELS[model_name]
    try:
        reps = loader(csv_path)
        ALL_REPORTS[model_name] = reps
        n = sum(len(v) for v in reps.values())
        print(f"{model_name} : {len(reps)} jobs, {n} reports CSV chargés")
    except FileNotFoundError:
        print(f"  ⚠ {model_name} : fichier introuvable → {csv_path}")
        ALL_REPORTS[model_name] = {}

ALL_MODEL_NAMES = list(MODEL_DIRS.keys()) + list(CSV_MODELS.keys())

"""## Prompts & Fonctions du Juge"""

JUDGE_SYSTEM = (
    "Tu es un expert senior en recrutement et en systèmes ATS.\n"
    "Tu évalues la qualité des rapports de matching CV↔poste.\n"
    "RÈGLES ABSOLUES :\n"
    "1. Raisonne ÉTAPE PAR ÉTAPE (chain-of-thought explicite).\n"
    "2. Scores entiers ou demi-entiers entre 0 et 10 (strict : max 7/10 si erreurs notables).\n"
    "3. Réponds UNIQUEMENT en JSON valide — aucun texte avant/après.\n"
    "4. Le champ 'reasoning' contient ton analyse détaillée (min 5 phrases).\n"
)

REFERENCE_SCHEMA = {
    "reasoning": "Analyse JD vs CV étape par étape",
    "required_skills": [{"skill": "nom", "importance": "critical|high|medium|low", "found_in_cv": True}],
    "expected_verdict": "Excellent Match|Good Match|Average Match|Poor Match|No Match",
    "expected_match_pct_range": [40, 60],
    "real_critical_gaps": ["compétence manquante critique"],
    "real_strengths": ["compétence réellement présente dans le CV"],
    "match_quality_summary": "Résumé en 2-3 phrases"
}

def generate_reference(jd_text, cv_text):
    """Le juge analyse JD + CV et produit son propre rapport de référence (gold standard)."""
    prompt = (
        f"## JOB DESCRIPTION\n{jd_text[:2000]}\n\n"
        f"## CV DU CANDIDAT\n{cv_text[:2000]}\n\n"
        "## TÂCHE\n"
        "Analyse ce CV par rapport à cette offre d'emploi et génère un rapport de référence "
        "objectif qui servira de vérité terrain pour évaluer d'autres rapports.\n\n"
        f"## Schéma JSON attendu\n{json.dumps(REFERENCE_SCHEMA, ensure_ascii=False, indent=2)}"
    )
    return call_with_retry([
        {"role": "system", "content": JUDGE_SYSTEM},
        {"role": "user",   "content": prompt}
    ])

EVAL_SCHEMA = {
    "reasoning": "Comparaison détaillée étape par étape (min 5 phrases)",
    "verdict_accuracy": "0-10 : le verdict du modèle correspond-il à la référence",
    "match_pct_accuracy": "0-10 : le match% est-il dans la plage attendue (±10 pts)",
    "hallucination_score": "0-10 : 10=aucune hallucination (gaps/forces inventés)",
    "reliability_score": "0-10 : les métriques sont-elles cohérentes entre elles",
    "error_score": "0-10 : 10=aucune erreur de classification (gaps manqués, sévérités fausses)",
    "overall": "Score global 0-10",
    "hallucinated_gaps": ["gaps cités par le modèle mais absents de la réalité"],
    "hallucinated_strengths": ["forces citées par le modèle mais non présentes dans le CV"],
    "missed_critical_gaps": ["gaps critiques réels non détectés par le modèle"],
    "verdict_match": True,
    "issues": ["description des erreurs ou incohérences détectées"]
}

def evaluate_model_report(reference, model_report, jd_text, cv_text):
    """Évalue le rapport d'un modèle par rapport au rapport de référence."""

    rep_summary = {
        "verdict":        (model_report.get("overall_assessment") or {}).get("verdict"),
        "match_pct":      (model_report.get("overall_assessment") or {}).get("match_pct"),
        "confidence":     (model_report.get("overall_assessment") or {}).get("confidence", {}).get("confidence_score"),
        "final_scores":   model_report.get("final_scores"),
        "critical_gaps":  model_report.get("critical_gaps", [])[:6],
        "strengths":      (model_report.get("profile_summary") or {}).get("strengths", [])[:5],
        "critical_weaknesses": (model_report.get("profile_summary") or {}).get("critical_weaknesses", [])[:5],
        "rationale":      str(model_report.get("decision_rationale") or "")[:400],
        "key_metrics": {
            k: (v.get("value") if isinstance(v, dict) else v)
            for k, v in (model_report.get("advanced_metrics_v6") or {}).items()
            if k in ["node_matching_cosine","weighted_f1","gap_score","jaccard_nodes","missing_critical_penalty"]
        }
    }
    prompt = (
        f"## JD (extrait)\n{jd_text[:800]}\n\n"
        f"## CV (extrait)\n{cv_text[:800]}\n\n"
        f"## RAPPORT DE RÉFÉRENCE (vérité terrain)\n"
        f"{json.dumps(reference, ensure_ascii=False, indent=2)[:1800]}\n\n"
        f"## RAPPORT DU MODÈLE À ÉVALUER\n"
        f"{json.dumps(rep_summary, ensure_ascii=False, indent=2)[:1800]}\n\n"
        "## TÂCHE\n"
        "Compare le rapport du modèle avec la référence. Détecte :\n"
        "- Hallucinations (gaps ou forces inventés non présents dans le CV/JD)\n"
        "- Erreurs de verdict ou de match%\n"
        "- Incohérences internes des métriques\n"
        "- Gaps critiques manqués\n\n"
        f"## Schéma JSON attendu\n{json.dumps(EVAL_SCHEMA, ensure_ascii=False, indent=2)}"
    )
    return call_with_retry([
        {"role": "system", "content": JUDGE_SYSTEM},
        {"role": "user",   "content": prompt}
    ])

print("Fonctions du juge prêtes")

"""## Préparation du dossier de sortie sur Drive"""

OUT_DIR = Path(DRIVE_ROOT) / OUT_DIR_NAME
OUT_DIR.mkdir(parents=True, exist_ok=True)
print(f"Dossier de sortie : {OUT_DIR}")

def save_judgment(job_id, cv_id, judgment_data):
    """Sauvegarde immédiate du jugement sur Drive."""
    filename = f"judgment_{job_id}_{cv_id}.json"
    out_path = OUT_DIR / filename
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(judgment_data, f, ensure_ascii=False, indent=2, default=str)
    return out_path

print("save_judgment() prête — chaque résultat sera écrit sur Drive dès qu'il est disponible")

"""## Boucle d'évaluation principale"""

pairs_to_evaluate = []
for job_id, entry in DATASET.items():
    jd_text = entry.get("description", "")
    if not jd_text.strip():
        continue
    for k in range(1, CVS_PER_JOB + 1):
        cv_id   = f"cv_{k}"
        cv_text = entry.get(cv_id, "")
        if not cv_text.strip():
            continue
        has_report = any(
            job_id in ALL_REPORTS.get(m, {}) and cv_id in ALL_REPORTS[m].get(job_id, {})
            for m in ALL_MODEL_NAMES
        )
        if has_report:
            pairs_to_evaluate.append((job_id, cv_id))

print(f"Paires à évaluer : {len(pairs_to_evaluate)}")

ALL_JUDGMENTS = {}
errors_log    = []

for job_id, cv_id in tqdm(pairs_to_evaluate, desc="Jugements"):
    pair_key = f"{job_id}_{cv_id}"
    entry    = DATASET[job_id]
    jd_text  = entry.get("description", "")
    cv_text  = entry.get(cv_id, "")


    reference = generate_reference(jd_text, cv_text)
    time.sleep(SLEEP_API)

    if reference is None:
        print(f"  ⚠ Référence échouée pour {pair_key}, paire ignorée")
        errors_log.append({"pair": pair_key, "step": "reference", "error": "LLM returned None"})
        continue

    judgment = {
        "pair_key":  pair_key,
        "job_id":    job_id,
        "cv_id":     cv_id,
        "timestamp": datetime.now().isoformat(),
        "provider":  PROVIDER,
        "model":     GROQ_MODEL if PROVIDER == "groq" else OPENROUTER_MODEL,
        "reference": reference,
        "models":    {}
    }


    for model_name in ALL_MODEL_NAMES:
        model_report = ALL_REPORTS.get(model_name, {}).get(job_id, {}).get(cv_id)
        if model_report is None:
            print(f"  ⚠ Pas de report pour {model_name} — ignoré")
            judgment["models"][model_name] = {"skipped": True, "reason": "no report found"}
            continue

        print(f"  → Évaluation {model_name}...")
        eval_result = evaluate_model_report(reference, model_report, jd_text, cv_text)
        time.sleep(SLEEP_API)

        if eval_result is None:
            print(f"  ⚠ Évaluation échouée pour {model_name}")
            errors_log.append({"pair": pair_key, "model": model_name, "step": "eval", "error": "LLM returned None"})
            eval_result = {"skipped": True, "reason": "LLM call failed"}

        judgment["models"][model_name] = eval_result


    saved_path = save_judgment(job_id, cv_id, judgment)
    ALL_JUDGMENTS[pair_key] = judgment
    print(f"  ✓ Sauvegardé → {saved_path.name}")
print(f"Évaluation terminée : {len(ALL_JUDGMENTS)} jugements sauvegardés dans {OUT_DIR}")
if errors_log:
    print(f"Erreurs rencontrées : {len(errors_log)} — voir errors_log")

"""## Agrégation des résultats"""

import numpy as np

SCORE_FIELDS = [
    "verdict_accuracy", "match_pct_accuracy",
    "hallucination_score", "reliability_score",
    "error_score", "overall"
]

def aggregate_judgments(all_judgments):
    agg = {}
    for pair_key, j in all_judgments.items():
        for model_name, eval_res in j.get("models", {}).items():
            if eval_res.get("skipped"):
                continue
            agg.setdefault(model_name, {f: [] for f in SCORE_FIELDS})
            for field in SCORE_FIELDS:
                val = eval_res.get(field)
                if isinstance(val, (int, float)):
                    agg[model_name][field].append(float(val))
    # Moyenne
    summary = {}
    for model_name, fields in agg.items():
        summary[model_name] = {
            f: round(float(np.mean(v)), 2) if v else None
            for f, v in fields.items()
        }
        summary[model_name]["n_evaluated"] = max(len(v) for v in fields.values()) if fields else 0
    return summary

AGG = aggregate_judgments(ALL_JUDGMENTS)

# ── Tableau récapitulatif ────────────────────────────────────────────────────
rows = []
for model_name, scores in AGG.items():
    row = {"Modèle": model_name}
    row.update(scores)
    rows.append(row)

if rows:
    from IPython.display import display, HTML
    import pandas as pd
    df = pd.DataFrame(rows).set_index("Modèle").sort_values("overall", ascending=False)
    display(HTML("<h3>Résumé des jugements</h3>"))
    green_cols = ["verdict_accuracy","match_pct_accuracy","hallucination_score",
                  "reliability_score","error_score","overall"]
    style = df.style.format(na_rep="N/A", precision=2)
    for c in green_cols:
        if c in df.columns:
            style = style.background_gradient(subset=[c], cmap="RdYlGn", vmin=0, vmax=10)
    display(style)
else:
    print("Aucun résultat à afficher.")

"""## Classement narratif"""

ranking = sorted(AGG.keys(), key=lambda m: AGG[m].get("overall") or 0, reverse=True)
MEDALS  = ["🥇 1er", "🥈 2ème", "🥉 3ème", "4ème", "5ème"]

html_parts = ['<div style="font-family:Arial,sans-serif;max-width:900px">']
html_parts.append('<h2 style="text-align:center;background:#2c3e50;color:white;'
                  'padding:15px;border-radius:8px">CLASSEMENT — QUALITÉ DES REPORTS</h2>')

for rank, model_name in enumerate(ranking):
    s = AGG[model_name]
    ov = s.get("overall") or 0
    medal = MEDALS[rank] if rank < len(MEDALS) else str(rank + 1)
    if ov >= 8:   qual, col = "Excellent",    "#1a7a4a"
    elif ov >= 6: qual, col = "Bon",          "#2e7d32"
    elif ov >= 4: qual, col = "Passable",     "#f57c00"
    else:          qual, col = "Insuffisant",  "#c62828"

    html_parts.append(f'<div style="border:2px solid {col};border-radius:10px;'
                      f'padding:15px;margin:15px 0">')
    html_parts.append(f'<h3 style="color:{col};margin:0">{medal} — {model_name} — '
                      f'{qual} ({ov}/10)</h3>')
    html_parts.append('<table style="width:100%;margin-top:10px">')

    labels = {
        "verdict_accuracy":    "Précision verdict",
        "match_pct_accuracy":  "Précision match%",
        "hallucination_score": "Anti-hallucination",
        "reliability_score":   "Fiabilité métriques",
        "error_score":         "Absence d'erreurs",
        "overall":             "Score global",
    }
    for field, label in labels.items():
        v = (s.get(field) or 0) * 10
        bc = "#4CAF50" if v >= 70 else "#FF9800" if v >= 50 else "#f44336"
        bar = f'<div style="background:{bc};width:{v:.0f}%;height:14px;border-radius:4px"></div>'
        html_parts.append(f'<tr><td style="width:200px;padding:3px 6px">{label}</td>'
                          f'<td style="width:60px">{s.get(field) or "N/A"}/10</td>'
                          f'<td>{bar}</td></tr>')
    html_parts.append("</table>")


    hallu_examples = []
    missed_examples = []
    for pair_key, j in ALL_JUDGMENTS.items():
        er = j.get("models", {}).get(model_name, {})
        hallu_examples += (er.get("hallucinated_gaps") or [])[:1]
        missed_examples += (er.get("missed_critical_gaps") or [])[:1]

    if hallu_examples:
        html_parts.append(f'<p style="color:#c62828"><b>Exemples hallucinations :</b> '
                          f'{" | ".join(hallu_examples[:3])}</p>')
    if missed_examples:
        html_parts.append(f'<p style="color:#f57c00"><b>Gaps manqués :</b> '
                          f'{" | ".join(missed_examples[:3])}</p>')

    html_parts.append(f'<p style="color:#555">Évaluations : {s.get("n_evaluated")} paires</p>')
    html_parts.append("</div>")

html_parts.append("</div>")
display(HTML("".join(html_parts)))

"""## Export agrégé sur Drive"""

if rows:
    summary_df = pd.DataFrame(rows).set_index("Modèle")
    summary_df.to_csv(OUT_DIR / "summary_scores.csv", float_format="%.4f")
    print(f"summary_scores.csv sauvegardé")


agg_out = {
    "timestamp":  datetime.now().isoformat(),
    "provider":   PROVIDER,
    "model":      GROQ_MODEL if PROVIDER == "groq" else OPENROUTER_MODEL,
    "max_rows":   MAX_ROWS,
    "n_pairs":    len(ALL_JUDGMENTS),
    "ranking":    ranking,
    "scores":     AGG,
    "errors":     errors_log,
}
with open(OUT_DIR / "aggregated_results.json", "w", encoding="utf-8") as f:
    json.dump(agg_out, f, ensure_ascii=False, indent=2, default=str)
print(f"aggregated_results.json sauvegardé")
print(f"\nTous les fichiers : {OUT_DIR}")
print("  • judgment_jobX_cvY.json  (un par paire — sauvegardés en temps réel)")
print("  • summary_scores.csv")
print("  • aggregated_results.json")