# -*- coding: utf-8 -*-
"""judgecode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kt_GN7SgerKmy-h7en-iYBn6P407EMK1
"""

from google.colab import drive
drive.mount('/content/drive')

import os, re, glob, time, json, csv, pandas as pd
from datetime import datetime
from groq import Groq

BASE_DIR   = '/content/drive/MyDrive/naive_baseline_groq_results'
CSV_PATH   = os.path.join(BASE_DIR, 'job-1 (1).csv')
OUTPUT_DIR = os.path.join(BASE_DIR, 'naive_baseline_results')
REPORT_DIR = os.path.join(BASE_DIR, 'report')

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(REPORT_DIR, exist_ok=True)


JUDGE_MODEL_ID = "qwen/qwen2.5-120b"
from google.colab import userdata
try:
    GROQ_API_KEY = os.environ.get('GROQ_API_KEY')
except Exception:
    import getpass
    GROQ_API_KEY = getpass.getpass('🔑 Clé Groq (gsk_...) : ')
os.environ['GROQ_API_KEY'] = GROQ_API_KEY
client = Groq(api_key=GROQ_API_KEY)


BASELINE_JSON_PATH = os.path.join(BASE_DIR, 'baseline_live_20260505_143552.json')
PIPELINE_DIR       = REPORT_DIR
PIPELINE_JSON_FILE = None


JOB_COL = "job_description_adequate"

if os.path.exists(CSV_PATH):
    df_data = pd.read_csv(CSV_PATH)
    df_data.index = range(len(df_data))
    print(f'✅ CSV chargé : {len(df_data)} lignes')
    print(f'   Colonnes : {list(df_data.columns)}')
else:
    df_data = pd.DataFrame()
    print(f'⚠️  CSV introuvable : {CSV_PATH}')


print(f'\n✅ Config :')
print(f'   BASE_DIR           : {BASE_DIR}')
print(f'   CSV_PATH           : existe = {os.path.exists(CSV_PATH)}')
print(f'   BASELINE_JSON_PATH : existe = {os.path.exists(BASELINE_JSON_PATH)}')
print(f'   PIPELINE_DIR       : existe = {os.path.exists(PIPELINE_DIR)}')
print(f'   JUDGE_MODEL_ID     : {JUDGE_MODEL_ID}')

pipeline_files = glob.glob(os.path.join(PIPELINE_DIR, 'report_job_*_cv_*.json'))
print(f'\n📂 {len(pipeline_files)} fichiers pipeline dans reports/')
for f in sorted(pipeline_files)[:5]:
    print(f'   {os.path.basename(f)}')
if len(pipeline_files) > 5:
    print(f'   ... et {len(pipeline_files) - 5} autres')


def groq_judge_call(messages: list, system: str,
                    temperature: float = 0.0,
                    max_retries: int = 5,
                    retry_wait: int = 30,
                    max_tokens: int = 1200) -> str:
    extra = {}
    if JUDGE_MODEL_ID in ("qwen/qwen3-32b", "qwen-qwq-32b"):
        extra["reasoning_format"] = "hidden"
    elif JUDGE_MODEL_ID in ("openai/gpt-oss-20b", "openai/gpt-oss-120b"):
        extra["reasoning_effort"] = "medium"

    for attempt in range(max_retries):
        try:
            completion = client.chat.completions.create(
                model=JUDGE_MODEL_ID,
                messages=[{"role": "system", "content": system}] + messages,
                temperature=temperature,
                max_tokens=max_tokens,
                stream=False,
                **extra,
            )
            return completion.choices[0].message.content
        except Exception as e:
            msg = str(e).lower()
            status_code = getattr(e, 'status_code', None)
            if status_code == 413 or '413' in msg or 'request too large' in msg:
                raise RuntimeError(
                    f"Requête trop grande (413) — réduis le texte. Détail: {str(e)[:200]}"
                ) from None
            elif any(k in msg for k in ("rate_limit", "rate limit", "too many requests", "429")):
                wait = retry_wait * (attempt + 1)
                print(f"    ⏳ Rate-limit — attente {wait}s (tentative {attempt+1}/{max_retries})...")
                time.sleep(wait)
            else:
                raise
    raise RuntimeError(f"Rate-limit persistant après {max_retries} tentatives.")

print("\n✅ Cellule init complète — prêt à lancer le juge")

!pip install groq

from google.colab import userdata


try:
    GROQ_API_KEY = userdata.get('GROQ_API_KEY')
    print('✅ Clé Groq chargée depuis les secrets Colab')
except Exception:
    import getpass
    GROQ_API_KEY = getpass.getpass('🔑 Entre ta clé API Groq (gsk_...) : ')

import os
os.environ['GROQ_API_KEY'] = GROQ_API_KEY
print('Token :', GROQ_API_KEY[:8] + '...')

import os
import re
import glob
import json
import csv
import numpy as np
import pandas as pd
from datetime import datetime


JUDGE_DIR = os.path.join(BASE_DIR, 'judge_results')
os.makedirs(JUDGE_DIR, exist_ok=True)

RUN_TIMESTAMP   = datetime.now().strftime('%Y%m%d_%H%M%S')
JUDGE_CSV_PATH  = os.path.join(JUDGE_DIR, f'judge_{RUN_TIMESTAMP}.csv')
JUDGE_JSON_PATH = os.path.join(JUDGE_DIR, f'judge_{RUN_TIMESTAMP}.json')

JUDGE_FIELDNAMES = [
    'job_idx', 'cv_col',
    'score_a', 'score_b',
    'judge_score', 'reasoning',
    'delta_a', 'delta_b', 'closer_system'
]

with open(JUDGE_CSV_PATH, 'w', newline='', encoding='utf-8-sig') as f:
    writer = csv.DictWriter(f, fieldnames=JUDGE_FIELDNAMES, extrasaction='ignore')
    writer.writeheader()

with open(JUDGE_JSON_PATH, 'w', encoding='utf-8') as f:
    json.dump([], f)

print(f'📂 Sorties juge :')
print(f'   CSV  → {JUDGE_CSV_PATH}')
print(f'   JSON → {JUDGE_JSON_PATH}\n')


def save_judge_result(r: dict):
    with open(JUDGE_CSV_PATH, 'a', newline='', encoding='utf-8-sig') as f:
        writer = csv.DictWriter(f, fieldnames=JUDGE_FIELDNAMES, extrasaction='ignore')
        writer.writerow(r)
    with open(JUDGE_JSON_PATH, 'r', encoding='utf-8') as f:
        data = json.load(f)
    data.append(r)
    with open(JUDGE_JSON_PATH, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)



INTER_REQUEST_DELAY = 12

def run_judge(job_text, cv_text, baseline_result, pipeline_result, job_idx, cv_col):

    score_a = baseline_result.get('score', 0)


    score_b = round(float(pipeline_result.get('match_pct', 0) or 0))

    system = """You are an expert HR evaluator. Your task is to assess the match between a CV and a job description, give your own honest match score, then compare it to two other systems.

## Scoring rules
- Score 0-100 reflecting how well the candidate fits the job requirements.
- 0  = completely unrelated profile.
- 50 = partial match, some key requirements missing.
- 100 = perfect match, all requirements met.
- Be strict and consistent. Base your score only on skills, experience level, and requirements alignment.

## Output format (strict JSON, no extra text)
{
  "judge_score": <integer 0-100>,
  "reasoning": "<2-3 sentences explaining your score>",
  "delta_a": <absolute difference |judge_score - score_A|>,
  "delta_b": <absolute difference |judge_score - score_B|>,
  "closer_system": "A" or "B" or "tie"
}"""

    user_content = f"""## Job Description
{str(job_text)[:900] if job_text else "Non disponible"}

## CV
{str(cv_text)[:900] if cv_text else "Non disponible"}

## Scores to evaluate
- System A (Baseline) : {score_a}/100
- System B (Pipeline) : {score_b}/100

Give your own honest judge_score first, then compute delta_a and delta_b."""

    raw = groq_judge_call(
        messages=[{"role": "user", "content": user_content}],
        system=system,
        temperature=0.0,
        max_tokens=1200
    )

    raw = raw.replace('```json', '').replace('```', '').strip()
    start = raw.find('{')
    end   = raw.rfind('}')

    if start == -1 or end == -1 or end <= start:
        raise ValueError(f"JSON incomplet ({len(raw)} chars): {raw[:300]}")

    try:
        parsed = json.loads(raw[start:end+1])
    except json.JSONDecodeError as e:
        raise ValueError(f"JSON malformé : {raw[start:end+1][:300]}")


    js = float(parsed.get('judge_score', 0))
    da = round(abs(js - score_a), 1)
    db = round(abs(js - score_b), 1)
    parsed['delta_a'] = da
    parsed['delta_b'] = db
    parsed['closer_system'] = 'A' if da < db else ('B' if db < da else 'tie')
    parsed['score_a']  = score_a
    parsed['score_b']  = score_b
    parsed['job_idx']  = job_idx
    parsed['cv_col']   = cv_col
    return parsed



with open(BASELINE_JSON_PATH, "r", encoding="utf-8") as f:
    baseline_data = json.load(f)

baseline_index = {(r["job_idx"], r["cv_col"]): r for r in baseline_data}
print(f"✅ Baseline chargé : {len(baseline_data)} résultats")

pipeline_index = {}
if PIPELINE_JSON_FILE and os.path.isfile(PIPELINE_JSON_FILE):
    with open(PIPELINE_JSON_FILE, "r", encoding="utf-8") as f:
        pipeline_list = json.load(f)
    for r in pipeline_list:
        key = (int(r["job_idx"]), r["cv_col"])
        pipeline_index[key] = r
    print(f"✅ Pipeline chargé depuis fichier unique : {len(pipeline_index)} résultats")
else:
    _pattern = re.compile(r"report_job_(\d+)_cv_(\d+)\.json$")
    for fpath in glob.glob(os.path.join(PIPELINE_DIR, "report_job_*_cv_*.json")):
        m = _pattern.search(os.path.basename(fpath))
        if not m:
            continue
        job_idx = int(m.group(1))
        cv_col  = f"cv_{int(m.group(2))}"
        with open(fpath, "r", encoding="utf-8") as f:
            pipeline_index[(job_idx, cv_col)] = json.load(f)
    print(f"✅ Pipeline chargé depuis dossier : {len(pipeline_index)} fichiers")

print(f"\n🔍 Exemples clés baseline : {list(baseline_index.keys())[:3]}")
print(f"🔍 Exemples clés pipeline : {list(pipeline_index.keys())[:3]}")


def extract_pipeline_summary(p: dict) -> dict:
    oa  = p.get("overall_assessment", {})
    cv6 = p.get("combo_scores_v6", {})
    pr  = p.get("pool_ranking", {})
    dr  = p.get("decision_rationale", {})
    return {
        "verdict"        : oa.get("verdict"),
        "match_pct"      : oa.get("match_pct"),                      # ← score utilisé pour B
        "combo_v6_final" : cv6.get("combo_v6_final", {}).get("value"),
        "pool_rank"      : pr.get("rank"),
        "pool_size"      : pr.get("pool_size"),
        "rationale"      : dr.get("why_this_verdict", ""),
    }


common_keys   = sorted(set(baseline_index) & set(pipeline_index))
only_baseline = set(baseline_index) - set(pipeline_index)
only_pipeline = set(pipeline_index) - set(baseline_index)

print(f"\n   Paires communes    : {len(common_keys)}")
if only_baseline: print(f"   ⚠️  Baseline seul   : {len(only_baseline)} paires")
if only_pipeline: print(f"   ⚠️  Pipeline seul   : {len(only_pipeline)} paires")

if len(common_keys) == 0:
    raise SystemExit("❌ Aucune paire commune.")


judge_results = []
judge_errors  = []

print(f'\n🔁 Lancement du juge sur {len(common_keys)} paires...\n')

for i, (job_idx, cv_col) in enumerate(common_keys, 1):
    b_res = baseline_index[(job_idx, cv_col)]
    p_raw = pipeline_index[(job_idx, cv_col)]
    p_res = extract_pipeline_summary(p_raw)

    job_text, cv_text = "", ""
    try:
        if not df_data.empty and job_idx in df_data.index:
            _j = df_data.loc[job_idx, JOB_COL]
            job_text = str(_j) if pd.notna(_j) else ""
            if cv_col in df_data.columns:
                _c = df_data.loc[job_idx, cv_col]
                cv_text = str(_c) if pd.notna(_c) else ""
    except Exception:
        pass

    score_a    = b_res.get('score', '?')
    match_pct  = p_res.get('match_pct', '?')            # ← affiché dans la progression
    print(f"  [{i}/{len(common_keys)}] Job #{job_idx} × {cv_col}"
          f" — A={score_a} | B(match_pct)={match_pct}"
          f" | rank={p_res.get('pool_rank','?')}/{p_res.get('pool_size','?')} ... ",
          end="", flush=True)

    try:
        r = run_judge(
            job_text=job_text, cv_text=cv_text,
            baseline_result=b_res, pipeline_result=p_res,
            job_idx=job_idx, cv_col=cv_col
        )
        judge_results.append(r)
        save_judge_result(r)
        js  = r.get('judge_score', '?')
        da  = r.get('delta_a', '?')
        db  = r.get('delta_b', '?')
        win = r.get('closer_system', '?')
        print(f"🏅 judge={js} | ΔA={da} | ΔB={db} | closer={win} 💾")
    except Exception as e:
        judge_errors.append({"job_idx": job_idx, "cv_col": cv_col, "error": str(e)})
        print(f"❌ {e}")

    if i < len(common_keys):
        time.sleep(INTER_REQUEST_DELAY)

print(f"\n✅ {len(judge_results)} jugements réussis, {len(judge_errors)} erreur(s)")



df_judge = pd.DataFrame(judge_results)
total_j  = len(df_judge)

SEP  = '═' * 65
sep2 = '─' * 65

print(f'\n{SEP}')
print("  RAPPORT D'ÉVALUATION — Groq-as-Judge (scores continus)")
print(SEP)
print(f'  Paires évaluées : {total_j}  |  {RUN_TIMESTAMP}')

judge_scores = df_judge['judge_score'].astype(float).tolist()
scores_a     = df_judge['score_a'].astype(float).tolist()
scores_b     = df_judge['score_b'].astype(float).tolist()

mae_a  = float(np.mean([abs(j - a) for j, a in zip(judge_scores, scores_a)]))
mae_b  = float(np.mean([abs(j - b) for j, b in zip(judge_scores, scores_b)]))
rmse_a = float(np.sqrt(np.mean([(j - a)**2 for j, a in zip(judge_scores, scores_a)])))
rmse_b = float(np.sqrt(np.mean([(j - b)**2 for j, b in zip(judge_scores, scores_b)])))
corr_a = float(np.corrcoef(judge_scores, scores_a)[0, 1])
corr_b = float(np.corrcoef(judge_scores, scores_b)[0, 1])

wins_a = (df_judge['closer_system'] == 'A').sum()
wins_b = (df_judge['closer_system'] == 'B').sum()
ties   = (df_judge['closer_system'] == 'tie').sum()

print(f'\n📊 SCORES MOYENS')
print(sep2)
print(f'  Juge (référence)        : {np.mean(judge_scores):.1f}/100')
print(f'  Baseline A (score)      : {np.mean(scores_a):.1f}/100')
print(f'  Pipeline B (match_pct)  : {np.mean(scores_b):.1f}/100')

print(f'\n📐 ÉCART AU JUGE  (plus bas = plus proche de la vérité)')
print(sep2)
print(f'  {"Métrique":<14} {"Baseline A":>12} {"Pipeline B":>12}')
print(f'  {"-"*38}')
print(f'  {"MAE":<14} {mae_a:>12.1f} {mae_b:>12.1f}   pts')
print(f'  {"RMSE":<14} {rmse_a:>12.1f} {rmse_b:>12.1f}   pts')
print(f'  {"Corrélation":<14} {corr_a:>12.3f} {corr_b:>12.3f}   (plus haut = mieux)')

print(f'\n🏅 VICTOIRES PAR PAIRE')
print(sep2)
print(f'  Baseline A plus proche  : {wins_a} fois')
print(f'  Pipeline B plus proche  : {wins_b} fois')
print(f'  Égalité                 : {ties} fois')

winner_mae  = "BASELINE A" if mae_a  < mae_b  else ("PIPELINE B" if mae_b  < mae_a  else "ÉGALITÉ")
winner_corr = "BASELINE A" if corr_a > corr_b else ("PIPELINE B" if corr_b > corr_a else "ÉGALITÉ")
winner_wins = "BASELINE A" if wins_a > wins_b else ("PIPELINE B" if wins_b > wins_a else "ÉGALITÉ")

print(f'\n🏆 VERDICT FINAL')
print(sep2)
print(f'  Meilleur MAE         : {winner_mae}')
print(f'  Meilleure corrélation: {winner_corr}')
print(f'  Plus de victoires    : {winner_wins}')


print(f'\n📋 TABLEAU COMPLET')
pd.set_option('display.max_colwidth', 120)
display(df_judge[['job_idx', 'cv_col', 'score_a', 'score_b',
                   'judge_score', 'delta_a', 'delta_b', 'closer_system', 'reasoning']])


final_timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

summary_csv = os.path.join(JUDGE_DIR, f'judge_summary_{final_timestamp}.csv')
df_judge.to_csv(summary_csv, index=False, encoding='utf-8-sig')
print(f'\n✅ CSV  → {summary_csv}')

summary_json = os.path.join(JUDGE_DIR, f'judge_summary_{final_timestamp}.json')
with open(summary_json, 'w', encoding='utf-8') as f:
    json.dump(judge_results, f, indent=2, ensure_ascii=False)
print(f'✅ JSON → {summary_json}')

if judge_errors:
    err_path = os.path.join(JUDGE_DIR, f'judge_errors_{final_timestamp}.json')
    with open(err_path, 'w', encoding='utf-8') as f:
        json.dump(judge_errors, f, indent=2, ensure_ascii=False)
    print(f'⚠️  Erreurs → {err_path}')

print(f"\n✅ {len(judge_results)} jugements réussis, {len(judge_errors)} erreur(s)")
print(f"💾 Résultats dans : {JUDGE_DIR}")