# -*- coding: utf-8 -*-
"""naive_baseline_groq_vs_gemma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ibx-bkkeIzn8AexV90nrsjoBU0PIi-LZ

# 🧠 Naive Baseline — CV × Job Matching + Comparaison Réalisme

| Module | Rôle |
|--------|------|
| **Gemma3:latest** (Ollama local) | Modèle de matching principal (gemma3:latest) |
| **Groq API** (LLaMA 3 70B) | Juge externe — évalue score · label · justification |
| **Comparaison ZIP** | Compare les résultats Groq vs rapport Gemma4b existant |

**Données** : `job(1).csv` — colonnes `job_adequate`, `cv1` … `cv5`  
**Métriques baseline** : score 0-100 · label · justification (2 phrases)  
**Résultats** : sauvegardés dans Google Drive

## ═══ BLOC 1 — 🔗 Google Drive & Chemins ═══
"""

from google.colab import drive
drive.mount('/content/drive')

import os
from pathlib import Path


CSV_PATH    = '/content/drive/MyDrive/naivtiegroq/job-1 (1).csv'
OUTPUT_DIR  = '/content/drive/MyDrive/naive_baseline_groq_results'


Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
print(f'✅ Drive monté')
print(f'   Source  : {CSV_PATH}')
print(f'   Sorties : {OUTPUT_DIR}')

"""## ═══ BLOC 2 — 📦 Installation des dépendances ═══"""

!pip install -q groq pandas requests psutil

"""## ═══ BLOC 3 — 🔑 Clé Groq API (gratuite) ═══

> **Obtenir une clé gratuite** : https://console.groq.com/keys  
> Modèle utilisé : `llama-3.3-70b-versatile` (quota gratuit généreux)
"""

from google.colab import userdata
import os


try:
    GROQ_API_KEY = userdata.get('GROQ_API_KEY')
    print('✅ Clé Groq chargée depuis les secrets Colab')
except Exception:
    import getpass
    GROQ_API_KEY = getpass.getpass('🔑 Entre ta clé Groq (gsk_...) : ')

os.environ['GROQ_API_KEY'] = GROQ_API_KEY
print('Clé :', GROQ_API_KEY[:8] + '...')

"""## ═══ BLOC 4 — ⚙️ Ollama : Installation & Démarrage (gemma3:latest) ═══

Reproduction fidèle de la procédure du fichier **GemmaSansGuide**.
"""

import subprocess, psutil

print("=" * 60)
print("  VÉRIFICATION GPU")
print("=" * 60)

try:
    result = subprocess.run(
        ['nvidia-smi', '--query-gpu=name,memory.total,memory.free', '--format=csv,noheader'],
        capture_output=True, text=True, check=True
    )
    print(f"  ✅ GPU : {result.stdout.strip()}")
except (FileNotFoundError, subprocess.CalledProcessError):
    print("  ❌ Pas de GPU — Runtime > Modifier le type d'exécution > T4 GPU")

ram = psutil.virtual_memory()
print(f"  RAM totale : {ram.total // (1024**3)} Go")
print(f"  RAM libre  : {ram.available // (1024**3)} Go")
print("=" * 60)

import subprocess, os, builtins, requests, time, re

print("=" * 60)
print("  INSTALLATION OLLAMA v0.6+ (script officiel)")
print("=" * 60)

!apt-get update -q && apt-get install -y zstd -q


subprocess.run('pkill -f ollama', shell=True, capture_output=True)
time.sleep(2)

result = subprocess.run(
    'curl -fsSL https://ollama.com/install.sh | sh',
    shell=True, capture_output=True, text=True
)
print(result.stdout[-500:] if result.stdout else "")

OLLAMA_BIN = None
for candidate in ['/usr/local/bin/ollama', '/usr/bin/ollama', '/root/.local/bin/ollama']:
    if os.path.exists(candidate):
        OLLAMA_BIN = candidate
        break

if not OLLAMA_BIN:
    raise RuntimeError("Ollama introuvable après installation")

ver = subprocess.run([OLLAMA_BIN, '--version'], capture_output=True, text=True)
print(f"  ✅ Version : {ver.stdout.strip()}")

m = re.search(r'(\d+)\.(\d+)', ver.stdout.strip())
if m:
    major, minor = int(m.group(1)), int(m.group(2))
    if major == 0 and minor < 6:
        raise RuntimeError(f"Version trop ancienne ({ver.stdout.strip()}) — /api/chat nécessite 0.6+")
    print(f"  ✅ Version OK ({major}.{minor} >= 0.6)")

builtins.OLLAMA_BIN = OLLAMA_BIN
print("=" * 60)

import subprocess, os

subprocess.run('apt-get install -y pciutils -q', shell=True, capture_output=True)

result = subprocess.run('nvidia-smi', shell=True, capture_output=True, text=True)
if result.returncode == 0:
    print("✅ GPU CUDA détecté")
    print(result.stdout[:400])
else:
    print("❌ GPU non visible — mode CPU")

os.environ['CUDA_VISIBLE_DEVICES']     = '0'
os.environ['OLLAMA_CUDA']              = '1'
os.environ['OLLAMA_FLASH_ATTENTION']   = '1'
os.environ['OLLAMA_NUM_PARALLEL']      = '1'
os.environ['OLLAMA_MAX_LOADED_MODELS'] = '1'

print("✅ Variables GPU configurées")

import subprocess, time, requests, os, builtins

print("=" * 60)
print("  DÉMARRAGE SERVEUR OLLAMA")
print("=" * 60)

subprocess.run('pkill -f "ollama serve"', shell=True, capture_output=True)
time.sleep(2)

env = os.environ.copy()
env['OLLAMA_HOST']              = '0.0.0.0:11434'
env['CUDA_VISIBLE_DEVICES']     = '0'
env['OLLAMA_FLASH_ATTENTION']   = '1'
env['OLLAMA_NUM_PARALLEL']      = '1'
env['OLLAMA_MAX_LOADED_MODELS'] = '1'

proc = subprocess.Popen(
    [builtins.OLLAMA_BIN, 'serve'],
    env=env,
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL
)
print(f"  PID : {proc.pid}")

for i in range(40):
    time.sleep(1)
    try:
        r = requests.get('http://localhost:11434/api/tags', timeout=2)
        if r.status_code == 200:
            print(f"  ✅ Serveur prêt après {i+1}s")
            break
    except:
        pass
else:
    raise RuntimeError("Ollama ne démarre pas après 40s")

models = [m['name'] for m in requests.get('http://localhost:11434/api/tags').json().get('models', [])]
print(f"  Modèles installés : {models if models else 'aucun'}")
print("=" * 60)

import subprocess, time, builtins, requests

OLLAMA_MODEL = "gemma3:4b"


print("=" * 60)
print(f"  TÉLÉCHARGEMENT : {OLLAMA_MODEL}")
print("=" * 60)

t0 = time.time()
result = subprocess.run([builtins.OLLAMA_BIN, 'pull', OLLAMA_MODEL], capture_output=False)
elapsed = round(time.time() - t0, 1)

if result.returncode == 0:
    print(f"  ✅ {OLLAMA_MODEL} prêt en {elapsed}s")
else:
    raise RuntimeError(f"Erreur pull {OLLAMA_MODEL}")

print("  ⏳ Test /api/chat avec le modèle...")
try:
    r = requests.post(
        'http://localhost:11434/api/chat',
        json={
            "model": OLLAMA_MODEL,
            "messages": [{"role": "user", "content": 'Reply only: {"ok": true}'}],
            "stream": False
        },
        timeout=120
    )
    print(f"  Status : {r.status_code}")
    print(f"  Réponse : {r.json().get('message', {}).get('content', '')[:80]}")
    print("  ✅ /api/chat FONCTIONNEL")
except Exception as e:
    print(f"  ❌ Erreur : {e}")

builtins.OLLAMA_MODEL = OLLAMA_MODEL
print("=" * 60)

"""## ═══ BLOC 5 — 📂 Chargement du CSV ═══"""

import pandas as pd

df_data = pd.read_csv(CSV_PATH)

JOB_COL = 'job_description_adequate'
CV_COLS = [c for c in ['cv_1', 'cv_2', 'cv_3', 'cv_4', 'cv_5'] if c in df_data.columns]

missing = [c for c in [JOB_COL] if c not in df_data.columns]
if missing:
    print(f'⚠️  Colonnes manquantes : {missing}')
    print(f'   Colonnes disponibles : {list(df_data.columns)}')
else:
    total_pairs = len(df_data) * len(CV_COLS)
    print(f'✅ CSV chargé : {len(df_data)} job(s) × {len(CV_COLS)} CV = {total_pairs} paires')
    display(df_data[[JOB_COL] + CV_COLS].head(3))

"""## ═══ BLOC 6 — 📝 Prompts & Fonctions de matching ═══

**Deux clients** :
- `run_matching_ollama()` → gemma3:latest via Ollama local
- `run_matching_groq()` → llama-3.3-70b via Groq API (juge externe)
"""

import json, re, requests, os
from datetime import datetime
from groq import Groq

# ── Prompt système partagé ────────────────────────────────────────────────────
SYSTEM_PROMPT = """
Tu es un recruteur expert.
Étant donné une offre d'emploi et un CV, évalue si le candidat est un bon match.
Retourne UNIQUEMENT un JSON valide, sans markdown ni backticks.

Structure exacte :
{
  "score": <entier de 0 à 100>,
  "label": "Strong Match" | "Good Fit" | "Moderate Match" | "Weak Match" | "Poor Match",
  "justification": "<exactement 2 phrases expliquant le verdict>"
}

Règles du label basées sur le score :
- 85-100 → Strong Match
- 70-84  → Good Fit
- 50-69  → Moderate Match
- 30-49  → Weak Match
- 0-29   → Poor Match
"""

GROQ_MODEL  = "llama-3.3-70b-versatile"
OLLAMA_URL  = "http://localhost:11434/api/chat"


def build_user_prompt(cv_text: str, job_text: str) -> str:
    return (
        f"OFFRE D'EMPLOI :\n---\n{str(job_text).strip()}\n\n"
        f"CV DU CANDIDAT :\n---\n{str(cv_text).strip()}\n\n"
        "Retourne le JSON maintenant."
    )

# ── Parsing robuste du JSON ───────────────────────────────────────────────────
def parse_json(raw: str) -> dict:
    clean = re.sub(r'```json|```', '', raw).strip()
    m = re.search(r'\{.*\}', clean, re.DOTALL)
    if m:
        return json.loads(m.group())
    raise ValueError(f'JSON introuvable dans : {raw[:300]}')

# ── Recalcul défensif du label à partir du score ─────────────────────────────
def score_to_label(score: int) -> str:
    if score >= 85: return 'Strong Match'
    if score >= 70: return 'Good Fit'
    if score >= 50: return 'Moderate Match'
    if score >= 30: return 'Weak Match'
    return 'Poor Match'


def run_matching_ollama(cv_text, job_text, job_idx, cv_col, temperature=0.1):
    """Appel Ollama local — gemma3:latest"""
    payload = {
        "model": builtins.OLLAMA_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": build_user_prompt(cv_text, job_text)},
        ],
        "stream": False,
        "options": {"temperature": temperature, "num_predict": 400}
    }
    resp = requests.post(OLLAMA_URL, json=payload, timeout=180)
    resp.raise_for_status()
    raw = resp.json()["message"]["content"]

    r = parse_json(raw)
    r['score']         = int(r.get('score', 0))
    r['label']         = r.get('label', score_to_label(r['score']))
    r['label_checked'] = score_to_label(r['score'])
    r['job_idx']       = int(job_idx)
    r['cv_col']        = cv_col
    r['model']         = builtins.OLLAMA_MODEL
    r['source']        = 'ollama'
    r['generated_at']  = datetime.now().isoformat()
    return r


_groq_client = Groq(api_key=os.environ['GROQ_API_KEY'])

def run_matching_groq(cv_text, job_text, job_idx, cv_col, temperature=0.1):
    """Appel Groq API — llama-3.3-70b-versatile (juge externe)"""
    completion = _groq_client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": build_user_prompt(cv_text, job_text)},
        ],
        max_tokens=400,
        temperature=temperature,
    )
    raw = completion.choices[0].message.content

    r = parse_json(raw)
    r['score']         = int(r.get('score', 0))
    r['label']         = r.get('label', score_to_label(r['score']))
    r['label_checked'] = score_to_label(r['score'])
    r['job_idx']       = int(job_idx)
    r['cv_col']        = cv_col
    r['model']         = GROQ_MODEL
    r['source']        = 'groq'
    r['generated_at']  = datetime.now().isoformat()
    return r

print('✅ Clients Ollama + Groq initialisés')
print(f'   Ollama → {builtins.OLLAMA_MODEL}')
print(f'   Groq   → {GROQ_MODEL}')

"""## ═══ BLOC 7 — 🚀 Lancement du Matching — Gemma3 + Groq ═══

> Chaque paire Job × CV est évaluée par **les deux modèles** en parallèle.
"""

# ══ CONFIGURATION ══════════════════════════════════════════════════════════════
TEST_ROWS   = 70
TEMPERATURE = 0.1
RUN_BOTH    = True
# ══════════════════════════════════════════════════════════════════════════════

print(f'  Jobs à traiter : {TEST_ROWS if TEST_ROWS else "tous"}')
print(f'  CVs par job    : {len(CV_COLS)}')
print(f'  Modèles actifs : Groq + {"Ollama" if RUN_BOTH else "—"}')

import csv
from datetime import datetime
import builtins

RUN_TIMESTAMP = datetime.now().strftime('%Y%m%d_%H%M%S')
LIVE_CSV      = os.path.join(OUTPUT_DIR, f'baseline_live_{RUN_TIMESTAMP}.csv')
LIVE_JSON     = os.path.join(OUTPUT_DIR, f'baseline_live_{RUN_TIMESTAMP}.json')

CSV_FIELDNAMES = ['job_idx', 'cv_col', 'source', 'model', 'label', 'score',
                  'label_checked', 'justification', 'generated_at']

with open(LIVE_CSV, 'w', newline='', encoding='utf-8-sig') as f:
    csv.DictWriter(f, fieldnames=CSV_FIELDNAMES, extrasaction='ignore').writeheader()
with open(LIVE_JSON, 'w', encoding='utf-8') as f:
    json.dump([], f)

print(f'📂 Sauvegarde incrémentale :')
print(f'   CSV  → {LIVE_CSV}')
print(f'   JSON → {LIVE_JSON}\n')


def save_result(r: dict):
    """Sauvegarde immédiate CSV + JSON"""
    with open(LIVE_CSV, 'a', newline='', encoding='utf-8-sig') as f:
        csv.DictWriter(f, fieldnames=CSV_FIELDNAMES, extrasaction='ignore').writerow(r)
    with open(LIVE_JSON, 'r', encoding='utf-8') as f:
        data = json.load(f)
    data.append(r)
    with open(LIVE_JSON, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


subset      = df_data if TEST_ROWS is None else df_data.head(TEST_ROWS)
total       = len(subset) * len(CV_COLS)
done        = 0
results_ollama = []
results_groq   = []
errors         = []

print(f'🔁 {len(subset)} job(s) × {len(CV_COLS)} CV = {total} paires\n')

for job_idx, row in subset.iterrows():
    job_text = row[JOB_COL]
    if pd.isna(job_text) or str(job_text).strip() == '':
        print(f'  ⏩ Job #{job_idx} — offre vide, ignoré')
        continue

    for cv_col in CV_COLS:
        cv_text = row.get(cv_col, '')
        if pd.isna(cv_text) or str(cv_text).strip() == '':
            print(f'  ⏩ Job #{job_idx} / {cv_col} — CV vide, ignoré')
            continue

        done += 1
        print(f'  [{done}/{total}] Job #{job_idx} × {cv_col}')


        try:
            rg = run_matching_groq(cv_text, job_text, job_idx, cv_col, TEMPERATURE)
            results_groq.append(rg)
            save_result(rg)
            print(f'    🟦 Groq   : {rg["label"]} | score={rg["score"]} | {rg["justification"][:70]}...')
        except Exception as e:
            errors.append({'job_idx': job_idx, 'cv_col': cv_col, 'source': 'groq', 'error': str(e)})
            print(f'    ❌ Groq   : {e}')


        if RUN_BOTH:
            try:
                ro = run_matching_ollama(cv_text, job_text, job_idx, cv_col, TEMPERATURE)
                results_ollama.append(ro)
                save_result(ro)
                print(f'    🟩 Gemma3 : {ro["label"]} | score={ro["score"]} | {ro["justification"][:70]}...')
            except Exception as e:
                errors.append({'job_idx': job_idx, 'cv_col': cv_col, 'source': 'ollama', 'error': str(e)})
                print(f'    ❌ Gemma3 : {e}')

        print()

print(f'\n✅ Groq   : {len(results_groq)} matching(s)')
print(f'✅ Gemma3 : {len(results_ollama)} matching(s)')
print(f'❌ Erreurs : {len(errors)}')

"""## ═══ BLOC 8 — 📊 Tableau de résultats ═══"""

import pandas as pd

all_results = results_ollama
df_results  = pd.DataFrame(all_results)

if df_results.empty:
    print('⚠️  Aucun résultat — vérifier les erreurs ci-dessus')
else:
    COLS = ['job_idx', 'cv_col', 'source', 'model', 'label', 'score', 'justification']
    pd.set_option('display.max_colwidth', 120)
    display(df_results[[c for c in COLS if c in df_results.columns]])

    print('\n--- Répartition des labels par source ---')
    print(df_results.groupby(['source', 'label']).size().to_string())

    print('\n--- Score moyen par source ---')
    print(df_results.groupby('source')['score'].describe().to_string())

    if  len(results_ollama) > 0:

        print('\n--- Meilleur CV par job (Gemma3) ---')
        dfo = pd.DataFrame(results_ollama)
        best_ollama = dfo.loc[dfo.groupby('job_idx')['score'].idxmax()][['job_idx','cv_col','label','score']].reset_index(drop=True)
        display(best_ollama)

"""## ═══ BLOC 9 — 🗜️ Lecture du ZIP — rapport Gemma4b existant ═══

Charger le fichier `amenigemma4b.zip` uploadé sur Drive et extraire les rapports JSON pour comparaison.
"""

# ══ CONFIGURATION ZIP ══════════════════════════════════════════════════════════
ZIP_PATH     = '/content/drive/MyDrive/amenigemma4b.zip'
ZIP_EXTRACT  = '/content/gemma4b_reports'
# ══════════════════════════════════════════════════════════════════════════════

print(f'ZIP source : {ZIP_PATH}')
print(f'Extraction : {ZIP_EXTRACT}')

import zipfile, os, json
from pathlib import Path

# ── Lister le contenu du ZIP ──────────────────────────────────────────────────
if not os.path.exists(ZIP_PATH):
    print(f'❌ ZIP introuvable : {ZIP_PATH}')
    print('   → Uploadez le fichier dans Google Drive et mettez à jour ZIP_PATH')
else:
    with zipfile.ZipFile(ZIP_PATH, 'r') as zf:
        all_names = zf.namelist()
        json_names = [n for n in all_names if n.endswith('.json')]
        print(f'✅ ZIP ouvert : {len(all_names)} fichiers total, {len(json_names)} JSON')
        print('   Exemple de chemins :')
        for n in json_names[:8]:
            print(f'   - {n}')

    # ── Extraction ────────────────────────────────────────────────────────────
    Path(ZIP_EXTRACT).mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(ZIP_PATH, 'r') as zf:
        zf.extractall(ZIP_EXTRACT)
    print(f'\n✅ Extraction terminée → {ZIP_EXTRACT}')

import glob, json, os

# ── Chercher tous les fichiers JSON de rapport ────────────────────────────────
report_files = glob.glob(os.path.join(ZIP_EXTRACT, '**', '*.json'), recursive=True)
print(f'📁 {len(report_files)} fichier(s) JSON trouvé(s)')

gemma4b_reports = []

for path in report_files:
    try:
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # Support liste de rapports OU rapport unique
        if isinstance(data, list):
            for item in data:
                item['_source_file'] = os.path.basename(path)
                gemma4b_reports.append(item)
        elif isinstance(data, dict):
            data['_source_file'] = os.path.basename(path)
            gemma4b_reports.append(data)
    except Exception as e:
        print(f'  ⚠️  Erreur lecture {path} : {e}')

print(f'\n✅ {len(gemma4b_reports)} rapport(s) Gemma4b chargé(s)')

if gemma4b_reports:
    print('\n── Aperçu des clés disponibles (premier rapport) ──')
    print(list(gemma4b_reports[0].keys()))

"""## ═══ BLOC 10 — 🔍 Normalisation des rapports Gemma4b ═══

Extraction des champs clés (`score`, `label`, `justification`) depuis la structure du rapport Gemma4b (format `overall_assessment` ou format baseline).
"""

import pandas as pd

def extract_report_fields(report: dict) -> dict:
    """
    Extrait les champs score/label/justification depuis différents formats de rapport :
    - Format pipeline Gemma (overall_assessment, match_pct, verdict)
    - Format baseline simple (score, label, justification)
    """
    out = {
        'job_idx':       report.get('job_idx', report.get('job_id', '?')),
        'cv_col':        report.get('cv_col',  report.get('cv_id',  '?')),
        'source':        'gemma4b_zip',
        'model':         report.get('model', 'gemma3:4b'),
        '_source_file':  report.get('_source_file', ''),
    }

    # ── Format pipeline (overall_assessment) ──────────────────────────────────
    oa = report.get('overall_assessment', {})
    if oa:
        match_pct = oa.get('match_pct', oa.get('match_percentage', None))
        verdict   = oa.get('verdict', oa.get('label', None))
        rationale = oa.get('rationale', oa.get('justification', ''))
        if match_pct is not None:
            out['score']         = int(float(str(match_pct).replace('%','').strip()))
            out['label']         = verdict or score_to_label(out['score'])
            out['justification'] = str(rationale)[:300]
            out['label_checked'] = score_to_label(out['score'])
            return out

    # ── Format baseline simple ─────────────────────────────────────────────────
    score = report.get('score', None)
    if score is not None:
        out['score']         = int(float(score))
        out['label']         = report.get('label', score_to_label(out['score']))
        out['justification'] = str(report.get('justification', ''))[:300]
        out['label_checked'] = score_to_label(out['score'])
        return out

    # ── Format scoring_results ─────────────────────────────────────────────────
    sr = report.get('scoring_results', report.get('phase3', {}))
    if sr:
        sc = sr.get('final_score', sr.get('score', None))
        if sc is not None:
            out['score']         = int(float(sc))
            out['label']         = sr.get('label', score_to_label(out['score']))
            out['justification'] = str(sr.get('summary', sr.get('justification', '')))[:300]
            out['label_checked'] = score_to_label(out['score'])
            return out

    # ── Fallback — pas de score reconnaissable ─────────────────────────────────
    out['score']         = -1
    out['label']         = 'N/A'
    out['justification'] = 'Format non reconnu — clés : ' + ', '.join(report.keys())[:200]
    out['label_checked'] = 'N/A'
    return out


# ── Normaliser tous les rapports ──────────────────────────────────────────────
gemma4b_normalized = [extract_report_fields(r) for r in gemma4b_reports]
df_gemma4b = pd.DataFrame(gemma4b_normalized)

valid = df_gemma4b[df_gemma4b['score'] >= 0]
print(f'✅ {len(valid)} rapport(s) Gemma4b normalisé(s) avec score valide')
print(f'⚠️  {len(df_gemma4b) - len(valid)} rapport(s) non reconnus')
if len(valid) > 0:
    display(valid[['job_idx','cv_col','source','label','score','justification']].head(10))

"""## ═══ BLOC 11 — ⚖️ Comparaison : Groq vs Gemma3 vs Gemma4b ═══

**Métriques de comparaison** :
- Distribution des scores (moyenne, médiane, std)
- Accord inter-modèles sur le label
- Paires convergentes vs divergentes
- 🏆 **Jugement Groq** : quel modèle est le plus réaliste ?
"""

import pandas as pd
import numpy as np

# ── Construire le dataframe unifié ───────────────────────────────────────────
frames = []

if results_ollama:
    frames.append(pd.DataFrame(results_ollama))
if len(valid) > 0:
    frames.append(valid.copy())

if not frames:
    print('⚠️  Aucune donnée disponible pour la comparaison')
else:
    df_all = pd.concat(frames, ignore_index=True)
    df_all['score'] = pd.to_numeric(df_all['score'], errors='coerce')

    print('═' * 60)
    print('  STATISTIQUES GLOBALES PAR SOURCE')
    print('═' * 60)
    stats = df_all.groupby('source')['score'].agg(['count','mean','median','std'])
    stats.columns = ['N', 'Moyenne', 'Médiane', 'Écart-type']
    display(stats.round(2))

    print('\n── Répartition des labels par source ──')
    label_dist = df_all.groupby(['source','label']).size().unstack(fill_value=0)
    display(label_dist)

    # ── Comparaison paire par paire (si plusieurs sources ont les mêmes paires) ──
    if 'groq' in df_all['source'].values and ('ollama' in df_all['source'].values or 'gemma4b_zip' in df_all['source'].values):
        df_groq_c  = df_all[df_all['source'] == 'groq'][['job_idx','cv_col','score','label']].rename(
            columns={'score':'score_groq','label':'label_groq'})

        compare_sources = [s for s in ['ollama','gemma4b_zip'] if s in df_all['source'].values]
        for src in compare_sources:
            df_src = df_all[df_all['source'] == src][['job_idx','cv_col','score','label']].rename(
                columns={'score':f'score_{src}','label':f'label_{src}'})

            df_merged = pd.merge(df_groq_c, df_src, on=['job_idx','cv_col'], how='inner')
            if not df_merged.empty:
                df_merged['diff_score']  = (df_merged['score_groq'] - df_merged[f'score_{src}']).abs()
                df_merged['label_agree'] = df_merged['label_groq'] == df_merged[f'label_{src}']

                print(f'\n── Groq vs {src} ({len(df_merged)} paires communes) ──')
                print(f'   Accord sur label : {df_merged["label_agree"].mean()*100:.1f}%')
                print(f'   Diff score moyen : {df_merged["diff_score"].mean():.1f} pts')
                print(f'   Diff score max   : {df_merged["diff_score"].max():.0f} pts')

                print('\n   Paires les plus divergentes (top 5) :')
                display(df_merged.nlargest(5, 'diff_score')[[
                    'job_idx','cv_col','score_groq',f'score_{src}','diff_score','label_groq',f'label_{src}'
                ]])

"""## ═══ BLOC 12 — 🏆 Jugement Groq : Quel modèle est le plus réaliste ? ═══

Groq (LLaMA 3.3 70B) analyse les résultats des deux autres modèles et détermine lequel est le plus **fiable et réaliste**.
"""

import json

def build_comparison_pairs(df_all: pd.DataFrame, max_pairs: int = 5) -> list:
    """
    Construit des paires de comparaison pour les mêmes job_idx × cv_col
    évalués par plusieurs modèles.
    """
    pairs = []
    grouped = df_all.groupby(['job_idx','cv_col'])
    count = 0
    for (job_idx, cv_col), grp in grouped:
        if len(grp) >= 2:
            entry = {'job_idx': job_idx, 'cv_col': cv_col, 'evaluations': []}
            for _, row in grp.iterrows():
                entry['evaluations'].append({
                    'source':        row['source'],
                    'model':         row.get('model','?'),
                    'score':         int(row['score']) if pd.notna(row['score']) else -1,
                    'label':         row.get('label','?'),
                    'justification': str(row.get('justification',''))[:200]
                })
            pairs.append(entry)
            count += 1
            if count >= max_pairs:
                break
    return pairs


JUDGE_SYSTEM_PROMPT = """
Tu es un expert en évaluation de systèmes d'IA pour le recrutement.
On te donne des évaluations de la même paire (offre d'emploi × CV) par plusieurs modèles.
Tu dois analyser ces évaluations et déterminer :
1. Quel modèle produit les scores les plus réalistes et calibrés
2. Lequel est le plus cohérent et justifié
3. Un verdict global de fiabilité

Retourne UNIQUEMENT un JSON valide :
{
  "most_reliable": "<source du modèle le plus fiable>",
  "reasoning": "<2-3 phrases d'analyse>",
  "reliability_scores": {"<source>": <0-100>, ...},
  "verdict": "<1 phrase de conclusion>"
}
"""

def judge_comparison(pairs: list) -> dict:
    """Demande à Groq de juger quelle évaluation est la plus réaliste"""
    prompt = f"""
Voici {len(pairs)} paires Job × CV évaluées par différents modèles :

{json.dumps(pairs, indent=2, ensure_ascii=False)}

Analyse ces évaluations. Quel modèle est le plus réaliste et fiable ?
Retourne le JSON maintenant.
"""
    completion = _groq_client.chat.completions.create(
        model="qwen/qwen3-32b",
        messages=[
            {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
            {"role": "user",   "content": prompt},
        ],
        max_tokens=800,
        temperature=0.2,
    )
    raw = completion.choices[0].message.content
    return parse_json(raw)


# ── Lancement du jugement ─────────────────────────────────────────────────────
if 'df_all' in dir() and not df_all.empty:
    comparison_pairs = build_comparison_pairs(df_all, max_pairs=5)

    if not comparison_pairs:
        print('⚠️  Aucune paire commune trouvée entre les modèles.')
        print('   Conseil : Augmenter TEST_ROWS pour avoir plus de paires communes.')
    else:
        print(f'🔎 {len(comparison_pairs)} paire(s) communes analysées par le juge Groq...\n')
        try:
            judgment = judge_comparison(comparison_pairs)
            print('═' * 60)
            print('  VERDICT DU JUGE GROQ (LLaMA 3.3 70B)')
            print('═' * 60)
            print(f'  🏆 Modèle le plus fiable : {judgment.get("most_reliable", "?")}')
            print(f'  📊 Scores de fiabilité   : {judgment.get("reliability_scores", {})}')
            print(f'  🔍 Analyse              : {judgment.get("reasoning", "?")}')
            print(f'  📌 Verdict final        : {judgment.get("verdict", "?")}')
            print('═' * 60)

            # Sauvegarde du jugement
            judgment_path = os.path.join(OUTPUT_DIR, f'judge_verdict_{RUN_TIMESTAMP}.json')
            with open(judgment_path, 'w', encoding='utf-8') as f:
                json.dump({
                    'judgment': judgment,
                    'pairs_analyzed': comparison_pairs,
                    'generated_at': datetime.now().isoformat()
                }, f, indent=2, ensure_ascii=False)
            print(f'\n💾 Jugement sauvegardé → {judgment_path}')

        except Exception as e:
            print(f'❌ Erreur jugement Groq : {e}')
else:
    print('⚠️  df_all non disponible — exécuter les blocs précédents')

"""## ═══ BLOC 13 — 💾 Sauvegarde finale dans Google Drive ═══"""

from datetime import datetime
import json, os

timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

if 'df_all' in dir() and not df_all.empty:
    # CSV global
    csv_all_path = os.path.join(OUTPUT_DIR, f'all_results_{timestamp}.csv')
    df_all.to_csv(csv_all_path, index=False, encoding='utf-8-sig')
    print(f'✅ CSV global   → {csv_all_path}')

    # JSON global
    json_all_path = os.path.join(OUTPUT_DIR, f'all_results_{timestamp}.json')
    all_data = results_groq + results_ollama + (gemma4b_normalized if gemma4b_normalized else [])
    with open(json_all_path, 'w', encoding='utf-8') as f:
        json.dump(all_data, f, indent=2, ensure_ascii=False)
    print(f'✅ JSON global  → {json_all_path}')

    # CSV séparés par source
    for src in df_all['source'].unique():
        df_src = df_all[df_all['source'] == src]
        src_path = os.path.join(OUTPUT_DIR, f'results_{src}_{timestamp}.csv')
        df_src.to_csv(src_path, index=False, encoding='utf-8-sig')
        print(f'✅ CSV {src:12s} → {src_path}')

if errors:
    err_path = os.path.join(OUTPUT_DIR, f'errors_{timestamp}.json')
    with open(err_path, 'w', encoding='utf-8') as f:
        json.dump(errors, f, indent=2, ensure_ascii=False)
    print(f'⚠️  Erreurs      → {err_path}')

print(f'\n📂 Tous les résultats dans : {OUTPUT_DIR}')

"""## 📋 Résumé de l'architecture

```
job(1).csv
    │
    ├── [Gemma3:latest] ── Ollama local (GPU T4)
    │       └── score · label · justification
    │
    ├── [LLaMA 3.3 70B] ── Groq API (gratuit)
    │       └── score · label · justification
    │
    └── amenigemma4b.zip
            └── rapports Gemma4b existants
                        │
                        ▼
              Comparaison 3 sources
                        │
                        ▼
           [Juge Groq] → verdict final
           "Quel modèle est le plus réaliste ?"
```

| Source | Modèle | Rôle |
|--------|--------|------|
| `ollama` | gemma3:latest | Matching principal |
| `groq` | llama-3.3-70b-versatile | Matching + **Juge** |
| `gemma4b_zip` | gemma3:4b | Référence existante (ZIP) |
"""